
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/jackkilrain/Library/Application Support/JetBrains/Toolbox/apps/CLion-Nova/ch-0/233.13871/CLion 2023.3 EAP.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:12 (project)"
    message: |
      The system is: Darwin - 23.2.0 - x86_64
...
